# Generated by Django 3.2.13 on 2022-07-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_users',
        ),
    ]
